# valid github action
# name: My first github action
# # now we need to mention when should this action should kick in
# # eg on push pull_request deployment_status
# on: [push]
# # now the github action would need to know what should it be doing
# # to specify it we have to mention it's job
# # here it is not compulsory that the 2 jobs will run one after another
# # to make it like that we have to convert it into a list with - prefix for each job
# jobs: 
#   print-hello-world:
#     runs-on: ubuntu-latest
#     steps: 
#       - run: echo "hello world"
#       - run: echo "hey this is the second step" # now these steps will run in sequence
#   print-hello-world2:
#     runs-on: ubuntu-latest
#     steps: 
#       - run: echo "hello world"
#       - run: echo "hey this is the second step"
#   # check-linting:
#   # unit-testing:


# name: My second github action
# on: [push]
# jobs:
#   build-app: 
#       runs-on: ubuntu-latest
#       steps: 
#         - uses: actions/checkout@v2
#         - uses: actions/setup-node@v2
#           with: 
#             node-version: '14.17.0'
#         - run: tree # if this runs perfectly then our project is cloned and we can start building things
#         - run: node -v

# Complete pipeline v2
name: My third github action
on: [push]
jobs:
  build-app: 
      runs-on: ubuntu-latest
      env:
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        VERCEL_TOKKEN: ${{ secrets.VERCEL_TOKEN }}
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}            
      steps: 
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with: 
            node-version: '14.17.0'
        - name: Project directory and version
          run: tree 
        - run: node -v
        - name: Install node_moduels
          run: yarn
        - name: Build the porject
          run : yarn build
        - name: Deploying the project
          run: yarn deploy
        - name: Setup finish
          run: echo "Setup finished"